on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - run: nix build nixpkgs#cacert
      - run: cp result/etc/ssl/certs/ca-bundle.crt cacert.pem
      - run: rm -rf result

      - uses: pho/action-calver@191a552404f6eb8abcb3f8005ca9d5b8e71349e0
        with:
          default_branch: "refs/heads/main"
          format: "YYYYMMDD"
          version_prefix: "v0."

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "automated: update cacert.pem"
          commit_author: "Workflow <github-actions[bot]@users.noreply.github.com>"
          tagging_message: "${{ env.PACKAGE_VERSION }}"
